grpc:
  server:
    name: "answer"
    weight: 100
    addr: ":19094"
    etcdTTL: 60
  client:
    question:
      endpoint: "discovery:///question"

mysql:
  dsn: "root:root@tcp(localhost:3306)/kstack"

etcd:
  endpoints:
    - "localhost:12379"

kafka:
  addrs:
    - "localhost:9094"